server:
  port: 8080
spring:
  datasource:
      password: speciality-app!
      url: jdbc:h2:mem:speciality_database
      username: speciality-app
logging:
  level:
      root: INFO
  pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
      file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
      name: ./logs/speciality-app.log